### ISSUE TITLE
Debian installer zst compression error

### ISSUE THREAD

**Issue by nikelui** [olivierkes/manuskript#1047]
I tried to install the latest version (0.14.0) on Debian but I get this error:

`dpkg-deb: error: archive 'manuskript-0.14.0-1.deb' uses unknown compression for member 'control.tar.zst', giving up`

The previous .deb version (0.13.1) installs just fine. After a bit of Google I discovered that Debian's dpkg [does not support zst compression](https://unix.stackexchange.com/questions/669004/zst-compression-not-supported-by-apt-dpkg).

I have found a [workaround](https://www.dolibarr.org/forum/t/unable-to-install-dolibarr-15-0-2-4-all-deb-on-debian-11-bullseye/22355), but you might just want to re-package the .deb with the right compression (.xz or .gz should be fine).

**Comment by TheJackiMonster** [comment]
I've probably packaged on an Ubuntu VM and just assumed it would work fine on Debian - my bad. ^^'

So I will need to package the .deb file on Debian then.

**Comment by nikelui** [comment]
A whole Debian VM might be overkill (unless you don't like Ubuntu anymore). Isn't there a way to just specify the compression of the .deb package? All I did was unpack the .deb, extract the .zst archives, re-compress them in .xz and re-package.

**Comment by TheJackiMonster** [comment]
The package should now be created using xz compression instead of the default from the packaging system. So this should solve the issue.

**Comment by phoe** [comment]
Still fails for me for https://github.com/olivierkes/manuskript/releases/download/0.14.0/manuskript-0.14.0-1.deb

```
┌─[root][helix][/home/phoe/Downloads]
└─▪ LANG=C dpkg -i manuskript-0.14.0-1.deb 
dpkg-deb: error: archive 'manuskript-0.14.0-1.deb' uses unknown compression for member 'control.tar.zst', giving up
dpkg: error processing archive manuskript-0.14.0-1.deb (--install):
 dpkg-deb --control subprocess returned error exit status 2
Errors were encountered while processing:
 manuskript-0.14.0-1.deb
```

Is there any newer version of this .deb file?

**Comment by TheJackiMonster** [comment]
> Still fails for me for https://github.com/olivierkes/manuskript/releases/download/0.14.0/manuskript-0.14.0-1.deb
> 
> ```
> ┌─[root][helix][/home/phoe/Downloads]
> └─▪ LANG=C dpkg -i manuskript-0.14.0-1.deb 
> dpkg-deb: error: archive 'manuskript-0.14.0-1.deb' uses unknown compression for member 'control.tar.zst', giving up
> dpkg: error processing archive manuskript-0.14.0-1.deb (--install):
>  dpkg-deb --control subprocess returned error exit status 2
> Errors were encountered while processing:
>  manuskript-0.14.0-1.deb
> ```
> 
> Is there any newer version of this .deb file?

Ah sorry for the confusion. So the proper compression will only be used on newer releases but I haven't manually repackaged the .deb file for 0.14.0 yet. I'll look into it.

**Comment by TheJackiMonster** [comment]
@phoe Please try again. I've repackaged the release 0.14.0 with the adjusted script to fix the current issue.
