### ISSUE TITLE
Crash when using bb10dark or bb10bright styles in settings

### ISSUE THREAD

**Issue by magicvince** [olivierkes/manuskript#467]
In parameters/setting, if I try to use bb10dark or bb10bright styles, manuskript crash on change.
If I change for another of this two styles, I can restart manuskript with the new style. Else, I have to remove style in config file before restarting.
The crash in the terminal windows : 

> Current thread 0x00007f31e0493700 (most recent call first):
>  File "/usr/share/manuskript/manuskript/main.py", line 89 in launch
>  File "/usr/share/manuskript/manuskript/main.py", line 102 in run
>  File "/usr/bin/manuskript", line 30 in <module>
> Erreur de segmentation

I'm working with LinuxMintDebianEdition (Debian Stretch)

**Comment by gedakc** [comment]
Hmm... this seems to be something that might be specific to the GNU/Linux distribution.

On my Kubuntu 16.04 computer I have neither the **bb10dark** nor the **bb10light** style.

The **styles** available on my computer are shown in the screen shot below:

![manuskript-settings-general-style-kubuntu16 04](https://user-images.githubusercontent.com/10405019/52180996-f2ebb280-27a9-11e9-8825-37c2b5ee3c77.png)

**Comment by magicvince** [comment]
It seems to be a good explanation, because I don't have the same styles.

**Comment by gedakc** [comment]
On your computer do you have some **styles** in common with my kubuntu 16.04 computer?

If so, do any of the common styles cause problems on your computer?

**Comment by magicvince** [comment]
I had locate who manage this style : qt5-style-plugin
I suppose you haven't the same version as me on your kubuntu. For me (Linux Mint Debian Edition - Debian Stretch) => 5.0.0+git16g7aa4764-1
So it's probably a qt bug but I have no time yet to investigate in this way.

**Comment by gedakc** [comment]
I would appear that the **Qt5** version (5.0.0) on your computer is much older than that on mine (5.5.1).  It is possible that the bug is fixed in the newer Qt5 versions.

Following are the packages installed on my computer that have "qt5" and "style" in the name.

```
$ dpkg -l | grep qt5 | grep style
ii  kde-style-oxygen-qt5                            4:5.5.5-0ubuntu1                                         amd64        Qt decoration for the Oxygen desktop theme
ii  kde-style-qtcurve-qt5:amd64                     1.8.18+git20160112-0cd6aae-1                             amd64        QtCurve widget style for applications based on Qt 5.x
```

**Comment by TheJackiMonster** [comment]
This crash happens with adwaita-qt if you don't install qgnomeplatform. That's the reason for multiple issues (#676 and #800) with similar behavior.

**Comment by kaptem** [comment]
Hello. I am still having this issue. It occurs on Adwaita-qt as well as Breeze. Here is my error log. 

`Fatal Python error: Segmentation fault

Current thread 0x00007f8780192740 (most recent call first):
  File "/home/user/manuskript/bin/../manuskript/main.py", line 243 in launch
  File "/home/user/manuskript/bin/../manuskript/main.py", line 309 in run
  File "/home/user/manuskript/bin/manuskript", line 13 in <module>

Extension modules: PyQt5.QtCore, PyQt5.QtGui, PyQt5.QtWidgets, PyQt5.QtNetwork, PyQt5.QtQml, PyQt5.QtBluetooth, PyQt5.QtDBus, PyQt5.QtDesigner, PyQt5.QtHelp, PyQt5.QtMultimedia, PyQt5.QtMultimediaWidgets, PyQt5.QtNfc, PyQt5.QtOpenGL, PyQt5.QtPositioning, PyQt5.QtLocation, PyQt5.QtPrintSupport, PyQt5.QtQuick, PyQt5.QtQuickWidgets, PyQt5.QtSensors, PyQt5.QtSerialPort, PyQt5.QtSql, PyQt5.QtSvg, PyQt5.QtTest, PyQt5.QtWebChannel, PyQt5.QtWebKit, PyQt5.QtWebKitWidgets, PyQt5.QtWebSockets, PyQt5.QtX11Extras, PyQt5.QtXml, PyQt5.QtXmlPatterns, lxml._elementpath, lxml.etree (total: 32)
Segmentation fault (core dumped)
`
